#add the files to index
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S1.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S2.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S3.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S4.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S5.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S6.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S7.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S8.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S9.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S10.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S11.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S12.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S13.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S14.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S15.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S16.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S17.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S18.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S19.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S20.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S21.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S22.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S23.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S24.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S25.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S26.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S27.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S28.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S29.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S30.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S31.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S32.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S33.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S34.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S35.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S36.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S37.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S38.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S39.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S40.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S41.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S42.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S43.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S44.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S45.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S46.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S47.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S48.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S49.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S50.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S51.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S52.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S53.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S54.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S55.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S56.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S57.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S58.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S59.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S60.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S61.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S62.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S63.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S64.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S65.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S66.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S67.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S68.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S69.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S70.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S71.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S72.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S73.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S74.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S75.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S76.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S77.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S78.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S79.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S80.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S81.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S82.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S83.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S84.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S85.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S86.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S87.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S88.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S89.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S90.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S91.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S92.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S93.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S94.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S95.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S96.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S97.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S98.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S99.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S100.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S101.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S102.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S103.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S104.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S105.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S106.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S107.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S108.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S109.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S110.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S111.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S112.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S113.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S114.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S115.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S116.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S117.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S118.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S119.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S120.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S121.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S122.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S123.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S124.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S125.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S126.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S127.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S128.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S129.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S130.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S131.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S132.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S133.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S134.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S135.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S136.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S137.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S138.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S139.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S140.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S141.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S142.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S143.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S144.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S145.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S146.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S147.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S148.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S149.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S150.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S151.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S152.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S153.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S154.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S155.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S156.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S157.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S158.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S159.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S160.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S161.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S162.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S163.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S164.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S165.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S166.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S167.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S168.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S169.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S170.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S171.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S172.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S173.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S174.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S175.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S176.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S177.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S178.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S179.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S180.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S181.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S182.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S183.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S184.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S185.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S186.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S187.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S188.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S189.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S190.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S191.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S192.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S193.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S194.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S195.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S196.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S197.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S198.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S199.txt
/home/shashank/Downloads/AILA-dataset/trec_fmt_statutes/S200.txt
